version: '3.8'

services:
  frontend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "8080:80" # Maps port 80 in the container to 8080 on the host
    container_name: softy-pinko-frontend

  backend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252" # Maps port 5252 inside the container to 5252 on the host
    container_name: softy-pinko-backend
